Document: mygestures
Title: Debian mygestures Manual
Author: <insert document author here>
Abstract: This manual describes what mygestures is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mygestures/mygestures.sgml.gz

Format: postscript
Files: /usr/share/doc/mygestures/mygestures.ps.gz

Format: text
Files: /usr/share/doc/mygestures/mygestures.text.gz

Format: HTML
Index: /usr/share/doc/mygestures/html/index.html
Files: /usr/share/doc/mygestures/html/*.html
