#ifndef MYGESTURES_ACTIONS_H_
#define MYGESTURES_ACTIONS_H_

#include "configuration.h"

#define ACTION_COUNT 19

/* Actions */
enum {
	ACTION_NULL,
	ACTION_EXIT_GEST,
	ACTION_EXECUTE,
	ACTION_ICONIFY,
	ACTION_KILL,
	ACTION_RECONF,
	ACTION_RAISE,
	ACTION_LOWER,
	ACTION_MAXIMIZE,
	ACTION_RESTORE,
	ACTION_TOGGLE_MAXIMIZED,
	ACTION_KEYPRESS,
	ACTION_ABORT,
	ACTION_WORKSPACE_LEFT,
	ACTION_WORKSPACE_RIGHT,
	ACTION_WORKSPACE_UP,
	ACTION_WORKSPACE_DOWN,
	ACTION_SHOW_OVERVIEW,
	ACTION_SHOW_APP_GRID,
	ACTION_LAST
};

const char *get_action_name(int action);

#endif
