#ifndef MYGESTURES_ACTIONS_H_
#define MYGESTURES_ACTIONS_H_

#include "configuration.h"

#define ACTION_COUNT 40

/* Actions */
enum {
	ACTION_NULL,
	ACTION_EXIT_GEST,
	ACTION_EXECUTE,
	ACTION_ICONIFY,
	ACTION_KILL,
	ACTION_RECONF,
	ACTION_RAISE,
	ACTION_LOWER,
	ACTION_MAXIMIZE,
	ACTION_RESTORE,
	ACTION_TOGGLE_MAXIMIZED,
	ACTION_KEYPRESS,
	ACTION_ABORT,
	ACTION_WORKSPACE_LEFT,
	ACTION_WORKSPACE_RIGHT,
	ACTION_WORKSPACE_UP,
	ACTION_WORKSPACE_DOWN,
	ACTION_SHOW_OVERVIEW,
	ACTION_SHOW_APP_GRID,
	ACTION_CLICK,
	ACTION_TOGGLE_FULLSCREEN,
	ACTION_SHOW_DESKTOP,
	ACTION_LOCK_SCREEN,
	ACTION_TERMINAL,
	ACTION_VOLUME_UP,
	ACTION_VOLUME_DOWN,
	ACTION_VOLUME_MUTE,
	ACTION_MEDIA_PLAY,
	ACTION_MEDIA_NEXT,
	ACTION_MEDIA_PREV,
	ACTION_WWW,
	ACTION_HOME,
	ACTION_EMAIL,
	ACTION_SEARCH,
	ACTION_CALCULATOR,
	ACTION_CONTROL_CENTER,
	ACTION_LOGOUT,
	ACTION_SCREENSHOT,
	ACTION_SCREENSHOT_WINDOW,
	ACTION_SCREENSHOT_AREA,
	ACTION_LAST
};

const char *get_action_name(int action);

void execute_click_agnostic(int button);

#endif
